---
- name: Install nginx
  hosts: ubuntu
  become: true

  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install nginx
    apt:
      name: nginx
      state: present

  - name: Insert Index Page
    template:
      src : index.html
      dest: /usr/share/nginx/html/index.html

  - name: Start NGiNX
    service:
      name: nginx
      state: started
